

const data = [
    {unit:'unit1-5', eng:'red', chi:'紅色', ex:'The tomato is red. (color)'},
    {unit:'unit1-5', eng:'green', chi:'綠色', ex:'The frog is green. (color)'},
    {unit:'unit1-5', eng:'blue', chi:'藍色', ex:'The sky is blue. (color)'},
    {unit:'unit1-5', eng:'black', chi:'黑色', ex:'The crayon is black. (color)'},
    {unit:'unit1-5', eng:'white', chi:'白色', ex:'The board is white. (color)'},
    {unit:'unit1-5', eng:'cat', chi:'貓', ex:'The cat likes'},
    {unit:'unit1-5', eng:'car', chi:'車', ex:''},
    {unit:'unit1-5', eng:'dog', chi:'狗', ex:''},
    {unit:'unit1-5', eng:'duck', chi:'鴨子', ex:''},
    {unit:'unit1-5', eng:'table', chi:'桌子', ex:''},
    {unit:'unit1-5', eng:'chair', chi:'椅子', ex:''},
    {unit:'unit1-5', eng:'crayon', chi:'蠟筆', ex:''},
    {unit:'unit1-5', eng:'pencil', chi:'鉛筆', ex:''},
    {unit:'unit1-5', eng:'book', chi:'書', ex:''},
    {unit:'unit1-5', eng:'egg', chi:'雞蛋', ex:''},
    {unit:'unit1-5', eng:'elephant', chi:'大象', ex:''},
    {unit:'unit1-5', eng:'fish', chi:'魚', ex:''},
    {unit:'unit1-5', eng:'farm', chi:'農場', ex:''},
    {unit:'unit1-5', eng:'train', chi:'火車', ex:''},
    {unit:'unit1-5', eng:'plane', chi:'飛機', ex:''},
    {unit:'unit1-5', eng:'puppet', chi:'玩偶', ex:''},
    {unit:'unit1-5', eng:'robot', chi:'機器人', ex:''},
    {unit:'unit1-5', eng:'balloon', chi:'氣球', ex:''},
    {unit:'unit1-5', eng:'teddy bear', chi:'泰迪熊', ex:''},
    {unit:'unit1-5', eng:'girl', chi:'女孩', ex:''},
    {unit:'unit1-5', eng:'guitar', chi:'吉他', ex:''},
    {unit:'unit1-5', eng:'hat', chi:'帽子', ex:''},
    {unit:'unit1-5', eng:'horse', chi:'馬', ex:''},
    {unit:'unit1-5', eng:'insect', chi:'昆蟲', ex:''},
    {unit:'unit1-5', eng:'ill', chi:'生病', ex:''},
    {unit:'unit1-5', eng:'mum', chi:'媽媽', ex:''},
    {unit:'unit1-5', eng:'dad', chi:'爸爸', ex:''},
    {unit:'unit1-5', eng:'brother', chi:'兄弟', ex:''},
    {unit:'unit1-5', eng:'sister', chi:'姐妹', ex:''},
    {unit:'unit1-5', eng:'grandpa', chi:'祖父', ex:''},
    {unit:'unit1-5', eng:'grandma', chi:'祖母', ex:''},
    {unit:'unit1-5', eng:'jug', chi:'水壺', ex:''},
    {unit:'unit1-5', eng:'juice', chi:'果汁', ex:''},
    {unit:'unit1-5', eng:'kangaroo', chi:'袋鼠', ex:''},
    {unit:'unit1-5', eng:'key', chi:'鑰匙', ex:''},
    {unit:'unit1-5', eng:'lion', chi:'獅子', ex:''},
    {unit:'unit1-5', eng:'lollipop', chi:'棒棒糖', ex:''},
    {unit:'unit1-5', eng:'happy', chi:'快樂', ex:''},
    {unit:'unit1-5', eng:'sad', chi:'難過', ex:''},
    {unit:'unit1-5', eng:'hungry', chi:'餓', ex:''},
    {unit:'unit1-5', eng:'thirsty', chi:'口渴', ex:''},
    {unit:'unit1-5', eng:'hot', chi:'熱', ex:''},
    {unit:'unit1-5', eng:'cold', chi:'冷', ex:''},
    {unit:'unit1-5', eng:'man', chi:'男人', ex:''},
    {unit:'unit1-5', eng:'mango', chi:'芒果', ex:''},
    {unit:'unit1-5', eng:'nose', chi:'鼻子', ex:''},
    {unit:'unit1-5', eng:'neck', chi:'脖子', ex:''},
    {unit:'unit1-5', eng:'orange', chi:'柳丁', ex:''},
    {unit:'unit1-5', eng:'octopus', chi:'章魚', ex:''},
    // {unit:'unit1-5', eng:'', chi:'', ex:''},
]

export default data