

const data = [
    {unit:'unit1', eng:'red', chi:'紅色'},
    {unit:'unit1', eng:'green', chi:'綠色'},
    {unit:'unit1', eng:'blue', chi:'藍色'},
    {unit:'unit1', eng:'black', chi:'黑色'},
    {unit:'unit1', eng:'white', chi:'白色'},
    {unit:'unit2', eng:'cat', chi:'貓'},
    {unit:'unit2', eng:'car', chi:'車'},
    {unit:'unit2', eng:'dog', chi:'狗'},
    {unit:'unit2', eng:'duck', chi:'鴨子'},
    {unit:'unit2', eng:'table', chi:'桌子'},
    {unit:'unit1-5', eng:'chair', chi:'椅子'},
    {unit:'unit1-5', eng:'crayon', chi:'蠟筆'},
    {unit:'unit1-5', eng:'pencil', chi:'鉛筆'},
    {unit:'unit1-5', eng:'book', chi:'書'},
    {unit:'unit1-5', eng:'egg', chi:'雞蛋'},
    {unit:'unit1-5', eng:'elephant', chi:'大象'},
    {unit:'unit1-5', eng:'fish', chi:'魚'},
    {unit:'unit1-5', eng:'farm', chi:'農場'},
    {unit:'unit1-5', eng:'train', chi:'火車'},
    {unit:'unit1-5', eng:'plane', chi:'飛機'},
    {unit:'unit1-5', eng:'puppet', chi:'玩偶'},
    {unit:'unit1-5', eng:'robot', chi:'機器人'},
    {unit:'unit1-5', eng:'balloon', chi:'氣球'},
    {unit:'unit1-5', eng:'teddy bear', chi:'泰迪熊'},
    {unit:'unit1-5', eng:'girl', chi:'女孩'},
    {unit:'unit1-5', eng:'guitar', chi:'吉他'},
    {unit:'unit1-5', eng:'hat', chi:'帽子'},
    {unit:'unit1-5', eng:'horse', chi:'馬'},
    {unit:'unit1-5', eng:'insect', chi:'昆蟲'},
    {unit:'unit1-5', eng:'ill', chi:'生病'},
    {unit:'unit1-5', eng:'mum', chi:'媽媽'},
    {unit:'unit1-5', eng:'dad', chi:'爸爸'},
    {unit:'unit1-5', eng:'brother', chi:'兄弟'},
    {unit:'unit1-5', eng:'sister', chi:'姐妹'},
    {unit:'unit1-5', eng:'grandpa', chi:'祖父'},
    {unit:'unit1-5', eng:'grandma', chi:'祖母'},
    {unit:'unit1-5', eng:'jug', chi:'水壺'},
    {unit:'unit1-5', eng:'juice', chi:'果汁'},
    {unit:'unit1-5', eng:'kangaroo', chi:'袋鼠'},
    {unit:'unit1-5', eng:'key', chi:'鑰匙'},
    {unit:'unit1-5', eng:'lion', chi:'獅子'},
    {unit:'unit1-5', eng:'lollipop', chi:'棒棒糖'},
    {unit:'unit1-5', eng:'happy', chi:'快樂'},
    {unit:'unit1-5', eng:'sad', chi:'難過'},
    {unit:'unit1-5', eng:'hungry', chi:'餓'},
    {unit:'unit1-5', eng:'thirsty', chi:'口渴'},
    {unit:'unit1-5', eng:'hot', chi:'熱'},
    {unit:'unit1-5', eng:'cold', chi:'冷'},
    {unit:'unit1-5', eng:'man', chi:'男人'},
    {unit:'unit1-5', eng:'mango', chi:'芒果'},
    {unit:'unit1-5', eng:'nose', chi:'鼻子'},
    {unit:'unit1-5', eng:'neck', chi:'脖子'},
    {unit:'unit1-5', eng:'orange', chi:'柳丁'},
    {unit:'unit1-5', eng:'octopus', chi:'章魚'},
    // {unit:'unit1-5', eng:'', chi:''},
]

export default data